### ISSUE TITLE
Add a basic user management

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#251]
We need the following basic functionality to be accessible via REST:
- create users (e.g. POST /api/v1/users)
- delete users (e.g. DELETE /api/v1/users) 
- Users need to be able to change their own password (e.g. POST /api/v1/account/password)

In addition we need to store the users in a embedded, file based Database (e.g. , SQLITE)

**Tasks**

- [x] Introduce the option to use a local database for the user management (#284)
- [x] Implement a user endpoint for creating and deleting users (#285)
- [x] Implement an account endpoint for managing the users account (#286)
