### ISSUE TITLE
Basic WebFrontend for the Configuration Server

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#283]
In order to manage the agent configurations in an easy way, a web frontend should be provided by the configuration server. Using the frontend, it should be possible to create, update and remove configuration files and roll them out to specific agent groups (agent mappings).

The basic version of the frontend should allow users to edit configuration files using a simple text editor. Easy-to-use UIs will be implemented in following tickets.

**Tasks**
- [x] Project Setup for Configuration Server UI  (#210)
- [x] Implement main layout for the configuration UI (#270)
- [x] Implement service for fetching data from the configuration server (#273)
- [x] Create view for loggin in into the config UI (#274)
- [x] Implement login logic and session management (#275)
- [x] Create view component for the agent mappings (#277)
- [x] Implement basic configuration view component (#278)
- [x] Implement configuration file view component (#279)
- [x] Implement logic for managing the configuration directory structure (#280)
- [x] Implement the logic for managing the configuration files (#281)
- [x] Implement search bar for the configuration view (#282)
