### ISSUE TITLE
Add stack-trace sampling

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#459]
It can be very hard to find a suitable instrumentation when only having a black-box look at applications.

For this prupose stack-trace sampling would be very useful: e.g., the user only needs to define an entrypoint scope, from which on the relevant calls will automatically be detected by performing stack-trace sampling.

From configuration perspective this could be realized as a special sensor which accepts scopes.

The hardest part will be to somehow reconstruct spans from the collect stack trace samples as spans and exporting them with OpenCensus.

**List of issues belonging to this epic:**

- [ ] Implement basic stack-trace sampling (#487)
- [ ] Use a dynamically configurable timer for stack trace sampling (#488)
- [ ] Make sampled trace work correctly with nested standard instrumentation (#490)
- [ ] Use Thread.dump for collecting stack traces (#491)
- [ ] Add documentation for stack trace sampling (#492)
