### ISSUE TITLE
Extending the configuration server and its UI to view existing configuration versions and their contents.

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#898]
This is an epic ticket about extending the configuration server and its UI to allow users to view existing versions of configuration files, as well as the content and state of the files for a given version.

Users should be able to see when a version was created by whom and what content a file had in a particular version.

This should enable users to easily track changes to the configuration files.

**List of issues belonging to this epic:**
- [x] Extend configuration UI by showing the version history of the workspace branch (#892)
- [x] Extend the configuration server by an endpoint for providing version information about the workspace branch (#893)
- [x] Enhance the endpoint to list existing files of the configuration server with the possibility to specify a version (#894)
- [x] Enhance the endpoint to fetch the file contents of the configuration server with the possibility to specify a version (#895)
- [x] Enhance the configuration UI so that the configuration view refers to a selected version (#896)
- [x] Extend the version history panel of the configuration UI to be able to switch to the live branch (#897)
